### ISSUE TITLE
[LOCALIZATION] Typo in contributors.md

### ISSUE THREAD

**Issue by anclywen** [WoD5E-Developers/.github#1]
There is a typo in the publisher's name
It should be Alis Games, there is Ali**a**s ​​Games

https://github.com/WoD5E-Developers/.github/blob/b1c4f3e078542725564916505aedcea52282d839/contributors.md?plain=1#L25

And by the way, thank you for your hard work in developing this project

**Comment by Veilza** [comment]
Fixed! Thank you for pointing this out - and sorry for taking a while to get to it, apparently I needed to turn on Issue notifications for this repository separately.

60c8b270c0a4bb4ad64cd9d562a74658e7751a63
